spring:
  application:
    name: myApp
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /my-health-check
        health-check-timeout: 30s
        healthCheckInterval: 20s
        enabled: true
        instanceId: ${spring.application.name}:${random.value}
        health-check-critical-timeout: 1m
server:
  port: 8080